### ISSUE TITLE
Add Settings

### ISSUE THREAD

**Issue by jonnitto** [dlubitz/vivomedia-neos-jpeg-pagespeed-optimization#1]
It would be great if there would be the possibility to edit a few settings:
* Sampling factor
* Turn the functionality entirely off (Like that I can activate the plugin only in some Context, e.g., Production)

**Comment by dlubitz** [comment]
I've added configuration to disable the image optimization. Default is enabled.
https://github.com/dlubitz/vivomedia-neos-jpeg-pagespeed-optimization/tree/2.1.2#configuration

IMHO the configuration of sampling factor doesn't make sense. Because target of this package is to implement Google PageSpeeds suggestion and this is 4:2:0. Moreover is would complicate the implementation of other image drivers, because the notation of the sampling factor seems not be standardized (4:2:0 vs 2x2,1x1,1x1 etc). I hope you are fine with that, otherwise PRs are welcome.

**Comment by jonnitto** [comment]
Should the setting not be 
```
VIVOMEDIA:
  GooglePageSpeed:
    JpegOptimization:
      enabled: false
```
and not 
```
VIVOMEDIA:
  GoogleAnalytics:
    JpegPagespeedOptimization:
      enabled: false
```
